[metadata]
name = mhcoin
version = 0.3.0

[options]
packages = find:
python_requires = >=3.9
install_requires =
    cryptography>=42.0.0
    click>=8.1.0
    pycryptodome>=3.20.0

[options.packages.find]
include = mhcoin*

[options.entry_points]
console_scripts =
    mhcoin = mhcoin.cli.main:cli
    mhcoin-core = mhcoin.desktop:main
